<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Análisis multivariante de la comunidad</title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="Este documento presenta una introducción al análisis multivariante de comunidades bióticas.">
  <meta name="generator" content="bookdown 0.1.16 and GitBook 2.6.7">

  <meta property="og:title" content="Análisis multivariante de la comunidad" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Este documento presenta una introducción al análisis multivariante de comunidades bióticas." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Análisis multivariante de la comunidad" />
  
  <meta name="twitter:description" content="Este documento presenta una introducción al análisis multivariante de comunidades bióticas." />
  

<meta name="author" content="Carlos Iván Espinosa">

  

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="medidas-de-similitud.html">
<link rel="next" href="ordenaciones-indirectas.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #0000ff; } /* Keyword */
code > span.ch { color: #008080; } /* Char */
code > span.st { color: #008080; } /* String */
code > span.co { color: #008000; } /* Comment */
code > span.ot { color: #ff4000; } /* Other */
code > span.al { color: #ff0000; } /* Alert */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #008000; font-weight: bold; } /* Warning */
code > span.cn { } /* Constant */
code > span.sc { color: #008080; } /* SpecialChar */
code > span.vs { color: #008080; } /* VerbatimString */
code > span.ss { color: #008080; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { } /* Variable */
code > span.cf { color: #0000ff; } /* ControlFlow */
code > span.op { } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #ff4000; } /* Preprocessor */
code > span.do { color: #008000; } /* Documentation */
code > span.an { color: #008000; } /* Annotation */
code > span.cv { color: #008000; } /* CommentVar */
code > span.at { } /* Attribute */
code > span.in { color: #008000; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href=" ">Análisis multivariante de la comunidad</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefacio</a></li>
<li class="chapter" data-level="" data-path="objetivos.html"><a href="objetivos.html"><i class="fa fa-check"></i>Objetivos</a></li>
<li class="chapter" data-level="1" data-path="medidas-de-similitud.html"><a href="medidas-de-similitud.html"><i class="fa fa-check"></i><b>1</b> Medidas de similitud</a><ul>
<li class="chapter" data-level="1.1" data-path="medidas-de-similitud.html"><a href="medidas-de-similitud.html#medidas-de-abundancia"><i class="fa fa-check"></i><b>1.1</b> Medidas de abundancia</a></li>
<li class="chapter" data-level="1.2" data-path="medidas-de-similitud.html"><a href="medidas-de-similitud.html#distancias-entre-sitios"><i class="fa fa-check"></i><b>1.2</b> Distancias entre sitios</a></li>
<li class="chapter" data-level="1.3" data-path="medidas-de-similitud.html"><a href="medidas-de-similitud.html#similitud"><i class="fa fa-check"></i><b>1.3</b> Similitud</a></li>
<li class="chapter" data-level="1.4" data-path="medidas-de-similitud.html"><a href="medidas-de-similitud.html#ejercicio-analisis-de-similitud"><i class="fa fa-check"></i><b>1.4</b> Ejercicio: Análisis de similitud</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="analisis-multivariado-de-la-composicion-de-la-comunidad.html"><a href="analisis-multivariado-de-la-composicion-de-la-comunidad.html"><i class="fa fa-check"></i><b>2</b> Análisis multivariado de la composición de la comunidad</a><ul>
<li class="chapter" data-level="2.1" data-path="analisis-multivariado-de-la-composicion-de-la-comunidad.html"><a href="analisis-multivariado-de-la-composicion-de-la-comunidad.html#agrupamiento-jerarquico-hierarchic-cluster"><i class="fa fa-check"></i><b>2.1</b> Agrupamiento Jerárquico (Hierarchic Cluster)</a></li>
<li class="chapter" data-level="2.2" data-path="analisis-multivariado-de-la-composicion-de-la-comunidad.html"><a href="analisis-multivariado-de-la-composicion-de-la-comunidad.html#interpretando-el-cluster"><i class="fa fa-check"></i><b>2.2</b> Interpretando el cluster</a><ul>
<li class="chapter" data-level="2.2.1" data-path="analisis-multivariado-de-la-composicion-de-la-comunidad.html"><a href="analisis-multivariado-de-la-composicion-de-la-comunidad.html#elegir-la-funcion-de-enlace"><i class="fa fa-check"></i><b>2.2.1</b> Elegir la función de enlace</a></li>
<li class="chapter" data-level="2.2.2" data-path="analisis-multivariado-de-la-composicion-de-la-comunidad.html"><a href="analisis-multivariado-de-la-composicion-de-la-comunidad.html#elegir-el-punto-de-corte"><i class="fa fa-check"></i><b>2.2.2</b> Elegir el punto de corte</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="analisis-multivariado-de-la-composicion-de-la-comunidad.html"><a href="analisis-multivariado-de-la-composicion-de-la-comunidad.html#ejercicio-2-analisis-de-clasificacion"><i class="fa fa-check"></i><b>2.3</b> Ejercicio 2: Análisis de clasificación</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ordenaciones-indirectas.html"><a href="ordenaciones-indirectas.html"><i class="fa fa-check"></i><b>3</b> Ordenaciónes Indirectas</a></li>
<li class="chapter" data-level="4" data-path="ordenaciones-directas-o-constrenidas.html"><a href="ordenaciones-directas-o-constrenidas.html"><i class="fa fa-check"></i><b>4</b> Ordenaciones Directas o Constreñidas</a></li>
<li class="chapter" data-level="" data-path="bibliografia.html"><a href="bibliografia.html"><i class="fa fa-check"></i>Bibliografia</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis multivariante de la comunidad</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="analisis-multivariado-de-la-composicion-de-la-comunidad" class="section level1">
<h1><span class="header-section-number">Capítulo 2</span> Análisis multivariado de la composición de la comunidad</h1>
<hr />
<p>Los índices de similitud nos permiten comparar las comunidades entre dos sitios, pero claramente cuando estudiamos las comunidades nuestros datos no son tan sencillos como lo que hemos utilizado hasta el momento. El organizar los datos de composición de la comunidad y poder interpretarlos en relación a otras comunidades, entender que comunidades son más similares entre sí, y saber si esta similitud o distancia es el resultado de unas respuestas al entorno pueden ser algunas de las cosas que podremos responder utilizando las técnicas de análisis multivariado de la comunidad. A continuación vamos a describir algunas técnicas de clasificación y ordenación que nos permitirán abordar estas temáticas.</p>
<p>Las técnicas de ordenación y clasificación son estrategias alternativas para simplificar los datos. La ordenación intenta simplificar los datos en un mapa que muestra las similitudes entre los puntos. La clasificación simplifica datos colocando los puntos similares en una misma clase o grupo Oksanen 2014<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a>.</p>
<p>Utilizaremos el paquete <em>Vegan</em> para los análisis de ordenación y clasificación, para mayor información puede referirse a Oksanen 2013<a href="#fn2" class="footnoteRef" id="fnref2"><sup>2</sup></a>.</p>
<div id="agrupamiento-jerarquico-hierarchic-cluster" class="section level2">
<h2><span class="header-section-number">2.1</span> Agrupamiento Jerárquico (Hierarchic Cluster)</h2>
<p>A continuación vamos a realizar un análisis Cluster (análisis de conglomerados) utilizando la función <em>hclust</em> del paquete <em>vegan</em>. La función hclust necesita una matriz de disimilitudes como entrada. El Análisis de conglomerados intenta generar conglomerados que tengan la máxima homogeneidad en cada grupo y la mayor diferencia entre los grupos.</p>
<p>Aunque la función <em>dist</em> nos permite calcular disimilitudes, para el análisis de comunidades biológicas utilizaremos la función <em>vegdist</em> del paquete <em>vegan</em>. Esta función nos permite calcular varios índices de disimilitud. El método de cálculo de la disimilitud por defecto es Bray-Curtis (<em>“bray”</em>).</p>
<p>Una de las características importantes del método Bray-Curtis es que varía entre 0 y 1, dos comunidades que no comparten ninguna especie tendrían 1 como resultado.</p>
<p>Calculemos una matriz de disimilitudes usando el método Bray-Curtis, utilizaremos los datos de Barro Colorado Island (BCI) cargados en el paquete <em>vegan</em>. Para eso necesitamos cargar el paquete y los datos de BCI, únicamente utilizaremos los datos de los primeros 10 sitios.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(vegan)
<span class="kw">data</span>(BCI)

dist&lt;-<span class="st"> </span><span class="kw">vegdist</span>(BCI[<span class="dv">1</span>:<span class="dv">10</span>,], <span class="dt">method=</span><span class="st">&quot;bray&quot;</span>)
dist[<span class="dv">1</span>:<span class="dv">10</span>]</code></pre></div>
<pre><code>##  [1] 0.2706682 0.3501647 0.3682008 0.3725079 0.3744186 0.3518519 0.3424346
##  [8] 0.4235706 0.3770140 0.2873051</code></pre>
<p>Podemos ver que el sitio 1 es 27% diferente al sitio 2, 35% al sitio 3, 36% al sitio 4 y así sucesivamente con los 10 sitios.</p>
<p>Con la matriz de disimilitudes calculada se puede analizar los puntos que conforman una agrupación. Utilizaremos los métodos de agrupación de la función <em>hclust</em> que nos propone tres métodos de agrupamiento: agrupación simple, agrupación completa y agrupación promedio.</p>
<p>Todos los métodos inician con el agrupamiento de las dos comunidades (dos sitios) más similares y a partir de esta primera comparación se continúa con el resto de puntos.</p>
<p>A continuación ejemplificaremos el cálculo de las distancias usando los tres métodos. Extraemos los cinco primeros sitios de la matriz de BCI y generamos un nuevo objeto (S_BCI). Con este nuevo objeto calculamos la distancia entre los cinco sitios.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">S_BCI&lt;-<span class="st"> </span>BCI[<span class="dv">1</span>:<span class="dv">5</span>,]
dist1&lt;-<span class="st"> </span><span class="kw">vegdist</span>(S_BCI, <span class="dt">method=</span><span class="st">&quot;bray&quot;</span>)
dist1</code></pre></div>
<pre><code>##           1         2         3         4
## 2 0.2706682                              
## 3 0.3501647 0.2873051                    
## 4 0.3682008 0.3149523 0.3244078          
## 5 0.3725079 0.3851064 0.3595041 0.3721619</code></pre>
<ol style="list-style-type: decimal">
<li><p>En base de la matriz de disimilitudes se busca el par de puntos que se encuentren más cercanos (menos disimiles). En nuestro caso el punto 1 y 2 tienen la distancia más baja 0.27. Una vez identificado, inicia el proceso de agrupación y es donde se diferencian los tres métodos.</p></li>
<li><p>Con el primer grupo generado debemos comenzar la construcción del resto de grupos, para esto construimos una nueva matriz de disimilitud calculando las distancias desde este primer grupo (1-2) al resto de sitios. El cálculo de esta distancia es dependiente del método.</p></li>
</ol>
<blockquote>
<p>Recuerde, para los sitios del 3 al 5 tendremos dos distancias, la distancia desde el sitio 1 y del sitio 2 a cada uno de estos sitios. Por tanto utilizaremos estas dos distancias para calcular la distancia desde el grupo.</p>
</blockquote>
<ul>
<li>En el método de agrupación simple la distancia entre el grupo y el sitio 3 será igual a la distancia más baja comparando entre la distancia del sitio 1 y el sitio 2. En el caso de la distancia al sitio 3 el valor mínimo es 0.287.<br />
</li>
<li>En el método completo el nuevo valor de distancia será el valor más alto, en este caso 0.350, y</li>
<li>En el método de agrupación promedio, obtenemos el valor promedio entre las distancias primer grupo y el sitio 3 en este caso 0.318 (Tabla 1).</li>
</ul>
<p><strong>Tabla 1.</strong> Cálculo de nuevas distancias entre el grupo 1 (sitio 1 y 2) y los sitios restantes. <em><strong>A. simple</strong></em>: cálculo de distancia mediante el método de agrupación simple. <strong><em>A. completa</em></strong>: cálculo de distancia mediante el método de agrupación completa. <strong><em>A. promedio</em></strong>: cálculo de distancia mediante el método de agrupación promedio.</p>
<table>
<colgroup>
<col width="14%" />
<col width="16%" />
<col width="14%" />
<col width="17%" />
<col width="20%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th>Sitios</th>
<th>Sitio 1</th>
<th>Sitio 2</th>
<th>A. Simple</th>
<th>A. Completa</th>
<th>A. Media</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p>Sitio 3</p></td>
<td><p>0.3501647</p></td>
<td><p>0.2873051</p></td>
<td><p>0.2873051</p></td>
<td><p>0.3501647</p></td>
<td><p>0.3187349</p></td>
</tr>
<tr class="even">
<td><p>Sitio 4</p></td>
<td><p>0.3682008</p></td>
<td><p>0.3149523</p></td>
<td><p>0.3149523</p></td>
<td><p>0.3682008</p></td>
<td><p>0.3415765</p></td>
</tr>
<tr class="odd">
<td><p>Sitio 5</p></td>
<td><p>0.3725079</p></td>
<td><p>0.3851064</p></td>
<td><p>0.3725079</p></td>
<td><p>0.3851064</p></td>
<td><p>0.3788071</p></td>
</tr>
</tbody>
</table>
<ol start="3" style="list-style-type: decimal">
<li>A partir de estos cálculos se construye nuevamente la matriz de distancia. Mostramos las nuevas matrices de distancias según el método de agrupación utilizado.</li>
</ol>
<p>Para el método de agrupación <strong>simple</strong></p>
<table style="width:58%;">
<colgroup>
<col width="9%" />
<col width="16%" />
<col width="15%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th>Sitio</th>
<th>Grupo1-2</th>
<th>Sitio 3</th>
<th>Sitio 4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p>3</p></td>
<td><p>0.2873051</p></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>4</p></td>
<td><p>0.3149523</p></td>
<td><p>0.3244078</p></td>
<td></td>
</tr>
<tr class="odd">
<td><p>5</p></td>
<td><p>0.3725079</p></td>
<td><p>0.3595041</p></td>
<td><p>0.3721619</p></td>
</tr>
</tbody>
</table>
<p>Para el método de agrupación <strong>completo</strong></p>
<table style="width:58%;">
<colgroup>
<col width="9%" />
<col width="16%" />
<col width="15%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th>Sitio</th>
<th>Grupo1-2</th>
<th>Sitio 3</th>
<th>Sitio 4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p>3</p></td>
<td><p>0.3501647</p></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>4</p></td>
<td><p>0.3682008</p></td>
<td><p>0.3244078</p></td>
<td></td>
</tr>
<tr class="odd">
<td><p>5</p></td>
<td><p>0.3851064</p></td>
<td><p>0.3595041</p></td>
<td><p>0.3721619</p></td>
</tr>
</tbody>
</table>
<p>Para el método de agrupación <strong>promedio</strong></p>
<table style="width:58%;">
<colgroup>
<col width="9%" />
<col width="16%" />
<col width="15%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th>Sitio</th>
<th>Grupo1-2</th>
<th>Sitio 3</th>
<th>Sitio 4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p>3</p></td>
<td><p>0.3187349</p></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>4</p></td>
<td><p>0.3415765</p></td>
<td><p>0.3244078</p></td>
<td></td>
</tr>
<tr class="odd">
<td><p>5</p></td>
<td><p>0.3788071</p></td>
<td><p>0.3595041</p></td>
<td><p>0.3721619</p></td>
</tr>
</tbody>
</table>
<ol start="4" style="list-style-type: decimal">
<li>Se repite el procedimiento, se busca los puntos que tienen la menor disimilitud en la nueva matriz y se vuelve a calcular las distancias desde este nuevo grupo al resto de grupos, esto se repite tantas veces hasta que todos los sitios están asociados.</li>
</ol>
<p>Podemos calcular directamente la agrupación utilizando la función <em>hclust</em>, y graficarlo con la función <em>plot</em>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfcol=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))

csim &lt;-<span class="st"> </span><span class="kw">hclust</span>(dist1, <span class="dt">method=</span><span class="st">&quot;single&quot;</span>)
ccom &lt;-<span class="st"> </span><span class="kw">hclust</span>(dist1, <span class="dt">method=</span><span class="st">&quot;complete&quot;</span>)
cpro &lt;-<span class="st"> </span><span class="kw">hclust</span>(dist1, <span class="dt">method=</span><span class="st">&quot;average&quot;</span>)

<span class="kw">plot</span>(csim, <span class="dt">cex.axis=</span><span class="fl">0.7</span>)
<span class="kw">plot</span>(ccom, <span class="dt">cex.axis=</span><span class="fl">0.7</span>)
<span class="kw">plot</span>(cpro, <span class="dt">cex.axis=</span><span class="fl">0.7</span>)</code></pre></div>
<div class="figure"><span id="fig:den3"></span>
<img src="AnalisisMultivarianteComunidad_files/figure-html/den3-1.png" alt="Dendrograma construido a partir de los 3 métodos de agrupación" width="672" />
<p class="caption">
Figure 2.1: Dendrograma construido a partir de los 3 métodos de agrupación
</p>
</div>
<p>Como podemos ver en la figura <a href="analisis-multivariado-de-la-composicion-de-la-comunidad.html#fig:den3">2.1</a> en todos los casos el primer grupo es el mismo, el grupo entre los sitios 1 y 2 con una disimilitud de 0.27, a partir de este punto los dendrogramas varían según el método utilizado. En el caso del método simple la disimilitud más baja es entre el grupo 1-2 y el sitio 3, con una disimilitud del 0.287. En el caso del método completo la disimilitud más baja se da entre el sitio 3 y 4 que conforman un segundo grupo con una disimilitud de 0.32. Finalmente, en el caso del método de promedio la menor disimilitud se da entre el grupo 1-2 y el sitio 3 con una disimilitud de 0.31 (Figura <a href="analisis-multivariado-de-la-composicion-de-la-comunidad.html#fig:den3">2.1</a>)</p>
<p>Los métodos de agrupamiento jerárquico (cluster) producen clasificaciones donde todas las observaciones se encuentran agrupadas de diferente forma. En los extremos todas las observaciones se encuentran agrupadas en una sola clase o cada observación conforma su clase privada, entre estos extremos las observaciones forman diferentes agrupamientos con niveles de disimilitud variables. Normalmente nos interesa tener un cierto número de clases con niveles de disimilitud establecido. La conformación de estos grupos se puede mostrar visualmente con función <strong>rect.hclust</strong> (Figura <a href="analisis-multivariado-de-la-composicion-de-la-comunidad.html#fig:dengr">2.2</a>)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">2</span>))
<span class="kw">plot</span>(ccom, <span class="dt">hang=</span>-<span class="fl">0.1</span>, <span class="dt">cex.axis=</span><span class="fl">0.7</span>, <span class="dt">cex.lab=</span><span class="fl">0.8</span>, <span class="dt">cex.main=</span><span class="fl">0.8</span>)
<span class="kw">rect.hclust</span>(ccom, <span class="dv">3</span>)</code></pre></div>
<div class="figure"><span id="fig:dengr"></span>
<img src="AnalisisMultivarianteComunidad_files/figure-html/dengr-1.png" alt="Dendrograma con número de grupos" width="672" />
<p class="caption">
Figure 2.2: Dendrograma con número de grupos
</p>
</div>
<p>Ahora podríamos obtener la pertenencia a un grupo y relacionarlo con otra variable explicativa, y analizar si la genración del grupo responde a algún factor.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">grupo &lt;-<span class="st"> </span><span class="kw">cutree</span>(ccom, <span class="dv">3</span>)
grupo</code></pre></div>
<pre><code>## 1 2 3 4 5 
## 1 1 2 2 3</code></pre>
</div>
<div id="interpretando-el-cluster" class="section level2">
<h2><span class="header-section-number">2.2</span> Interpretando el cluster</h2>
<p>El análisis de conglomerados (cluster) no es un test estadístico, y como vimos hay varios factores que pueden afectar la generación de los grupos <span class="citation">(Borcard, Gillet, and Legendre <a href="#ref-Borcard2011">2011</a>)</span>, por lo que debemos ser consientes de lo que obtenemos como resultado. POdemos usar la función <code>summary()</code> para ver la información que tenemos luego de haber utilizado el <code>hclust</code>, estos datos pueden ser utilizados para interpretar el agrupamiento <span class="citation">(Borcard, Gillet, and Legendre <a href="#ref-Borcard2011">2011</a>)</span>.</p>
<p>Como vimos anteriormente el investigador puede decidir, en función de su experiencia y de los arboles generados, cuantos grupos se generan dentro del árbol y que metodo de agrupamiento utilizar, sin embargo, podemos utilizar algunas funciones que nos permitan determinar grupos consistentes.</p>
<div id="elegir-la-funcion-de-enlace" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Elegir la función de enlace</h3>
<p>Una forma que podemos utilizar para definir los grupos es la distancia Cofenética. Esta distancia es calculada como la distancia entre dos objetos de un mismo grupo en el dendrograma, la distancia desde el primer objeto al segundo objeto pasando por el nodo de unión de los dos objetos es la distancia Cofenética. Una matriz cofenética es una matriz que representa las distancias cophenéticas entre todos los pares de objetos. Con esta matriz podemos correlacionar con la matriz de disimilitud original. El método con la correlación cofenética más alta puede ser vista como la que produjo el mejor modelo de agrupación para la matriz de distancia.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Calculamos la matriz cofenética para cada método de</span>
<span class="co">#agrupamiento</span>

csim_coph &lt;-<span class="st"> </span><span class="kw">cophenetic</span>(csim)
cpro_coph &lt;-<span class="st"> </span><span class="kw">cophenetic</span>(cpro)
ccom_coph &lt;-<span class="st"> </span><span class="kw">cophenetic</span>(ccom)

<span class="co">#Calculamos la correlación</span>
<span class="kw">cor</span>(csim_coph, dist1); <span class="kw">cor</span>(cpro_coph, dist1);<span class="kw">cor</span>(ccom_coph, dist1)</code></pre></div>
<pre><code>## [1] 0.8143114</code></pre>
<pre><code>## [1] 0.846916</code></pre>
<pre><code>## [1] 0.7487461</code></pre>
<p>Según estos datos el método promedio es el método que produce un mejor agrupamiento.</p>
<p>Otra forma de evaluar el mejor método es calcular la distancia de Gower, calculado como la suma de los cuadrados de la diferencia entre la matriz de distancia y la distancia Cofenética, el menor valor significa que es el mejor método de agrupamiento.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sim_gow &lt;-<span class="st"> </span><span class="kw">sum</span>((dist1-csim_coph)^<span class="dv">2</span>)
pro_gow &lt;-<span class="st"> </span><span class="kw">sum</span>((dist1-cpro_coph)^<span class="dv">2</span>)
com_gow &lt;-<span class="st"> </span><span class="kw">sum</span>((dist1-ccom_coph)^<span class="dv">2</span>)

sim_gow; pro_gow; com_gow</code></pre></div>
<pre><code>## [1] 0.007860928</code></pre>
<pre><code>## [1] 0.003917673</code></pre>
<pre><code>## [1] 0.01068659</code></pre>
<p>En este caso vemos que la decisión usando la distancia de Gower y la Cofenética es la misma, el método promedio produce el mejor agrupamiento. Sin embargo, no siempre el resultado es consistente entre los dos métodos.</p>
<blockquote>
<p>Este proceso nos ha permitido obtener la mejor función de enlace, sin embargo, para definir cuales son los subconjuntos de datos (tener un punto de corte) se puede utilizar algunas otras herramientas.</p>
</blockquote>
</div>
<div id="elegir-el-punto-de-corte" class="section level3">
<h3><span class="header-section-number">2.2.2</span> Elegir el punto de corte</h3>
<p>Como vimos anteriormente yo puedo definir un punto de corte para generar los grupos o puedo decidir cuantos grupos, sin embargo, este procedimiento es subjetivo. Podemos utilizar alguna información que nos permita tomar decisiones fundamentadas.</p>
<p>Podemos utilizar la <strong>silhouette width (anchura de la silueta)</strong> para medir el grado de pertenencia de un objeto a su agrupación, basado en la distancia media entre este objeto y todos los objetos de la agrupación a la que se pertenece, en comparación con la misma medida calculada para el siguiente grupo más cercano <span class="citation">(Borcard, Gillet, and Legendre <a href="#ref-Borcard2011">2011</a>)</span>. Utilizaremos la función <code>siluette</code> del paquete <strong>cluster</strong>. La salida de esta función varía entre 1 y -1. Los valores negativos significan que los objetos correspondientes probablemente se han colocado en un grupo erróneo.</p>
<p>A continuación el proceso utilizado:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(cluster)

<span class="co">#Generamos un vector vacío para colocar los valores </span>
<span class="co"># medios de la anchura de la silueta (mas)</span>
mas &lt;-<span class="st"> </span><span class="kw">numeric</span>(<span class="kw">nrow</span>(S_BCI))

<span class="co">#Calculamos y ponemos el &lt;mas&gt; en el vector generado</span>
for( k in <span class="dv">2</span>:<span class="st"> </span>(<span class="kw">nrow</span>(S_BCI)-<span class="dv">1</span>)){
    sil &lt;-<span class="st"> </span><span class="kw">silhouette</span>(<span class="kw">cutree</span>(ccom, <span class="dt">k=</span>k), dist1)
  mas[k] &lt;-<span class="st"> </span><span class="kw">summary</span>(sil)$avg.width
}

<span class="co"># Analizamos cual es el mejor punto de corte</span>
k.best &lt;-<span class="st"> </span><span class="kw">which.max</span>(mas)

<span class="co"># Graficamos</span>
<span class="kw">plot</span>(<span class="dv">1</span>:<span class="kw">nrow</span>(S_BCI), mas, <span class="dt">type =</span> <span class="st">&quot;h&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Número de grupos óptimo&quot;</span>, 
     <span class="dt">xlab =</span> <span class="st">&quot;Número de grupos (k)&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Media de la anchura de la silueta&quot;</span>)
<span class="kw">axis</span>(<span class="dv">1</span>, k.best, <span class="kw">paste</span>(<span class="st">&quot;Optimo&quot;</span>, k.best, <span class="dt">sep=</span><span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>  ), 
     <span class="dt">col=</span><span class="st">&quot;red&quot;</span>, <span class="dt">font=</span><span class="dv">2</span>, <span class="dt">col.axis=</span><span class="st">&quot;red&quot;</span>)
<span class="kw">points</span>(k.best, <span class="kw">max</span>(mas), <span class="dt">pch=</span><span class="dv">16</span>, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>, <span class="dt">cex=</span><span class="fl">1.5</span>)</code></pre></div>
<p><img src="AnalisisMultivarianteComunidad_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cat</span>(<span class="st">&quot;&quot;</span>, <span class="st">&quot;Número óptimo de grupos k=&quot;</span>, k.best, <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>,
    <span class="st">&quot;Con un valor medio de anchura de la silueta de&quot;</span>, <span class="kw">max</span>(mas), <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)</code></pre></div>
<pre><code>##  Número óptimo de grupos k= 2 
##  Con un valor medio de anchura de la silueta de 0.1130222</code></pre>
<p>A partir de este punto podría utilizar otras herramientas para definir el número de grupos. Ahora nos interesa saber si los grupos están balanceados y bien delimitados. Podemos utilizar el gráfico de la silueta</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">k&lt;-<span class="st"> </span><span class="dv">2</span>
cutg &lt;-<span class="st"> </span><span class="kw">cutree</span>(ccom, <span class="dt">k=</span>k)
sil &lt;-<span class="st"> </span><span class="kw">silhouette</span>(cutg, dist1)
sil.o &lt;-<span class="st"> </span><span class="kw">sortSilhouette</span>(sil)

<span class="kw">rownames</span>(sil.o) &lt;-<span class="st"> </span><span class="kw">row.names</span>(S_BCI)[<span class="kw">attr</span>(sil.o, <span class="st">&quot;iOrd&quot;</span>)]

<span class="kw">plot</span>(sil.o, <span class="dt">main=</span> <span class="st">&quot;Gráfico de silueta&quot;</span>, <span class="dt">cex.names =</span> <span class="fl">0.8</span>, 
     <span class="dt">col =</span> cutg<span class="dv">+3</span>, <span class="dt">nmax.lab=</span><span class="dv">100</span>)</code></pre></div>
<p><img src="AnalisisMultivarianteComunidad_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Al parecer no ha sido el mejor ejemplo, sin embargo, podemos ver que los 2 grupos han sido consistentes. Vamos a probar con nuevos datos.</p>
</div>
</div>
<div id="ejercicio-2-analisis-de-clasificacion" class="section level2">
<h2><span class="header-section-number">2.3</span> Ejercicio 2: Análisis de clasificación</h2>
<p>Con el fin de determinar si existen agrupamientos de herbaceas dentro de una parcela permanente de 9ha en la Reserva Ecológica Arenillas realizaremos un análisis de Agrupamiento (Cluster).</p>
<p>Para esto disponemos de una matriz con datos de la composición de la comunidad que puede ser descargado <a href="https://github.com/Ciespinosa/AnalisisMultivariante/herbaceas.xlsx">aquí</a>.</p>
<p>Los datos corresponden a un levantamiento de la vegetación de herbáceas en 4 tiempos distintos; final de invierno (abril 2012), estación seca (noviembre 2012), inicio del invierno (diciembre 2012), invierno (enero 2013). Se levantaron 4 cuadrantes de 0.5x0.5 m en cada vértice y centro de la parcela permanente de 9 hectáreas (113 muestras).</p>
<p>Con estos datos:</p>
<ol style="list-style-type: decimal">
<li><p>Calcular una matriz de disimilitud utilizando la distancia de Bray-Curtis.</p></li>
<li><p>Definir la mejor función de enlace para los tres métodos.</p></li>
<li><p>Definir usando la función silhouette cuantos grupos deberían generarse.</p></li>
<li><p>Realizar un gráfico del cluster y mostrar los grupos con la función rect.hclust</p></li>
<li><p>Evaluar si los grupos obtenidos responden a alguna de las variables de especies leñosas</p></li>
<li><p>Graficar las coordenadas <strong>“x”</strong> y <strong>“y”</strong> de las parcelas y colorear cada punto de acuerdo al grupo al que pertenece. Esto nos permitirá identificar si existe un patrón espacial en la generación de los grupos.</p></li>
</ol>

</div>
</div>
<h3>Bibliografia</h3>
<div id="refs" class="references">
<div id="ref-Borcard2011">
<p>Borcard, Daniel, Francois Gillet, and Pierre Legendre. 2011. <em>Numerical Ecology with R</em>. doi:<a href="https://doi.org/10.1007/978-0-387-78171-6">10.1007/978-0-387-78171-6</a>.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p><a href="http://cc.oulu.fi/~jarioksa/opetus/metodi/sessio3.pdf" class="uri">http://cc.oulu.fi/~jarioksa/opetus/metodi/sessio3.pdf</a><a href="analisis-multivariado-de-la-composicion-de-la-comunidad.html#fnref1">↩</a></p></li>
<li id="fn2"><p><a href="http://cc.oulu.fi/~jarioksa/opetus/metodi/vegantutor.pdf" class="uri">http://cc.oulu.fi/~jarioksa/opetus/metodi/vegantutor.pdf</a><a href="analisis-multivariado-de-la-composicion-de-la-comunidad.html#fnref2">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="medidas-de-similitud.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ordenaciones-indirectas.html" class="navigation navigation-next " aria-label="Next page""><i class="fa fa-angle-right"></i></a>

<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/03-cluster.Rmd",
"text": "Edit"
},
"download": ["AnalisisMultivarianteComunidad.pdf", "AnalisisMultivarianteComunidad.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
